### ISSUE TITLE
16: tx-overwinter-active. Code:-26

### ISSUE THREAD

**Issue by 317482454** [zerocurrencycoin/bitcore-lib-zero#2]
16: tx-overwinter-active. Code:-26
bitcore-lib-zero
Has this library been invalidated?

**Comment by R3DEY3UK** [comment]
No, it's fine. If you find a bug please report it.

**Comment by CryptoForge** [comment]
This library has not been updated to create transactions post overwinter.

It has however been updated to decode transactions post sapling.
